# Generated by Django 5.2 on 2025-05-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedPatent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent', models.CharField(default='ПАТЕНТ_НЕ_УКАЗАН', max_length=255)),
                ('sentence', models.TextField(default='')),
                ('classification', models.CharField(default='Недостатки', max_length=100)),
            ],
            options={
                'db_table': 'classified_weaknesses',
            },
        ),
    ]
